<?php
// $Id

function billing_perm() {
	return array('access billing');
} // function billing_perm()

/**
* Display help and module information
* @param path which path of the site we're displaying help
* @param arg array that holds the current path as would be returned from arg() function
* @return help text for the path
*/
function billing_help($path, $arg) {
  $output = '';
  switch ($path) {
    case "admin/help#billing":
      $output = '<p>'.  t("Access and manage your credits, monthly and yearly payments.") .'</p>';
      break;
  }
  return $output;
} // function billing_help

/**
* Generate HTML for the billing block
* @param op the operation from the URL
* @param delta offset
* @returns block HTML 
*/
function billing_block($op='list', $delta=0) {
  // listing of blocks, such as on the admin/block page
  if ($op == "list") {
    $block[0]["info"] = t("Billing");
    return $block;
  } else if ($op == 'view') {
  // our block content
    // content variable that will be returned for display
    $block_content = '';

    // Get today's date
    $today = getdate();

    // calculate midnight one week ago
    $start_time = mktime(0, 0, 0,$today['mon'],
                               ($today['mday'] - 7), $today['year']);

    // we want items that occur only on the day in question, so 
    //calculate 1 day
    $end_time = $start_time + 86400;
    // 60 * 60 * 24 = 86400 seconds in a day

    $result =  db_query("SELECT nid, title, created FROM {node}");
    while ($links = db_fetch_object($result)) {
      $block_content .= l($links->title, 'node/'.$links->nid) . '<br />';
    }
    // check to see if there was any content before setting up the block
    if ($block_content == '') {
      // no content from a week ago, return nothing.
      return;
    }
    // set up the block
    $block['subject'] = 'Billing';
    $block['content'] = $block_content;
    return $block;
  }
}

	// not a hook
function billing_admin() {

  $form['billing_maxdisp'] = array(
    '#type' => 'textfield',
    '#title' => t('Maximum number of links'),
    '#default_value' => variable_get('billing_maxdisp', 3),
    '#size' => 2,
    '#maxlength' => 2,
    '#description' => t("The maximum number of links to display in the block."),
    '#required' => TRUE,
  );

  return system_settings_form($form);
}

function billing_menu() {

  $items = array();

  $items['admin/settings/billing'] = array(
    'title' => 'Billing module settings',
    'description' => 'Access and manage your credits, monthly and yearly payments.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('billing_admin'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
   );

  return $items;
}

