---
version: '3'

services:
  drupal:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./legacy-database:/legacy-database"
      - "./legacy-files:/legacy-files"
      - "./drupal/custom-modules:/var/www/html/sites/default/modules"
      - "./drupal/custom-themes:/var/www/html/sites/default/themes"
      - "./drupal/custom-libraries:/var/www/html/sites/default/libraries"
      - "./drupal/settings:/local-settings"
      - "./drupal/scripts:/scripts"
    ports:
      - "80"
    links:
      - mysql:mysql
    working_dir: /var/www/html

  # Database server
  mysql:
    image: mysql:5
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
    volumes:
      - "mysql:/var/lib/mysql"
      - ./mysql/cnf:/etc/mysql/conf.d

# Specifying the network name makes it predictable on all environments,
# for example when running ./scripts/migrate-all.sh, or when running browser
# tests on a CI environment, or any other tasks which requires external
# docker containers to connect to our network.
# This network (legacy_tdj_default) has been previously created in
# ./scripts/deploy.sh
# See https://github.com/docker/compose/issues/3736.
networks:
  default:
    external:
      name: legacy_tdj_default

volumes:
  mysql:
